export const environment = {
    GRAPHQL_URL: process.env["NEXT_PUBLIC_GRAPHQL_URL"],
    HYGRAPH_MUTATION_TOKEN: process.env["NEXT_PUBLIC_HYGRAPH_MUTATION_TOKEN"],
    HYGRAPH_QUERY_TOKEN: process.env["NEXT_PUBLIC_HYGRAPH_QUERY_TOKEN"]
}